bot:
  api_key: 466074967:AAHAEaiBAHz5im_pdzNmW1gR1NGOAAR5JB8
  username: MltTempBot
  hook_url: https://tlgbot.mlg.ddemo.ru/hook
  cert: /etc/ssl/mycerts/tlgbot.mlg.crt
apps:
  vkontakte:
    client_id: 6223471
    secret_key: ilsUQvhc50T6nEdsjzWS
  facebook:
    app_id: 1851063158255307
    app_secret: 38e43b5ab78044815bcc51314fdb20a0
    access_token: EAAaTiDoBLssBAJg2qrTZAsL2vcpOCeoT5UgXal7ZCXygmP6k0ZApUER0QyLcf5MR5V8bZBoZA9uQ2qwOJ8qdn9waE8FxZCZC2Bpxerfgi7wh6y5MDzoJd6avZCPU9P81OndZCx2UxscM2fjnGoaOzlCxY4qufKbU00J6qyZAwB9r10zZBEKSx2L0esL
    default_graph_version: v2.10
hostname: http://tlgbot.mlg.ddemo.ru
