buttons:
  menu:
    label: \xF0\x9F\x93\x8B Меню
    description: выход в главное меню
    command: /main
  email:
    label: \xE2\x9C\x89 Указать email
    description: ввести email пользователя в системе SlavaBot
    command: /email
  repeatcode:
    label: \xF0\x9F\x94\x84 Отправить код повторно
    description: повторная отправка кода активации
    command: /email
  post:
    label: \xF0\x9F\x93\x83 Опубликовать
    description: опубликовать новый пост в ваших группах
    command: /post
  settings:
    label: \xF0\x9F\x94\xA7 Настройка
    description: настройки публикации
    command: /settings
  time:
    label: \xF0\x9F\x95\x9C Часовой пояс
    description: установить часовой пояс
    command: /time
timezones:
    active: \xE2\x9C\x94
    buttons:
      UTC+2:
        value: Europe/Kaliningrad
        label: Калининград
      UTC+3:
        value: Europe/Moscow
        label: Москва
      UTC+4:
        value: Europe/Astrakhan
        label: Астрахань
      UTC+5:
        value: Asia/Yekaterinburg
        label: Екатеринбург
      UTC+6:
        value: Asia/Novosibirsk
        label: Новосибирск
      UTC+7:
        value: Asia/Barnaul
        label: Барнаул
      UTC+8:
        value: Asia/Irkutsk
        label: Иркутск
      UTC+9:
        value: Asia/Chita
        label: Чита
      UTC+10:
        value: Asia/Vladivostok
        label: Владивосток
