timezones:
  UTC+2:
    value: Europe/Kaliningrad
    label: Калининград
  UTC+3:
    value: Europe/Moscow
    label: Москва
  UTC+4:
    value: Europe/Astrakhan
    label: Астрахань
  UTC+5:
    value: Asia/Yekaterinburg
    label: Екатеринбург
  UTC+6:
    value: Asia/Novosibirsk
    label: Новосибирск
  UTC+7:
    value: Asia/Barnaul
    label: Барнаул
  UTC+8:
    value: Asia/Irkutsk
    label: Иркутск
  UTC+9:
    value: Asia/Chita
    label: Чита
  UTC+10:
    value: Asia/Vladivostok
    label: Владивосток
social:
  facebook:
    app_id: '169360780313874'
    app_secret: '38e43b5ab78044815bcc51314fdb20a0'
    version: 'v2.10'
    permissions:
      0: 'public_profile'
      1: 'publish_actions'
      2: 'manage_pages'
      3: 'publish_pages'
      4: 'pages_show_list'
      5: 'read_insights'
      6: 'pages_messaging'
      #7: 'pages_messaging_subscriptions'

      #5: 'feed'
      #5: 'subscribed_apps'
  vk:
    app_id: '6223471'
    app_secret: 'ilsUQvhc50T6nEdsjzWS'
bot_url: 'http://t.me/slavarubot'
defaul_tarif:
  id: 4
  period: 10
postsNotifications:
  0: 'Вы давно не постили!'
  1: 'Самое время добавить новый пост!'
  2: 'Может запостим?'
  3: 'Подписчики требуют постов!'

#  Конфиг для выгрузки постов
ReportsConfig:
  # Интервал от времени запуска в минутах
  period: 15
  # Адрес для получения выгрузки
  wsdl: 'http://sm.mlg.ru/services/CubusService.svc?wsdl'
