#%RAML 1.0
#HTML генерируем через: raml2html generate -i frontend/web/api.raml -o frontend/web/api.html
title: SalesBot
version: v1.0
baseUri: 'http://app.slavabot.ru/'
mediaType: application/json
description: "REST-api для обмена данными c SalesBot."

/rest/user/v1:
  displayName: Работа с пользователем SlavaBot
  /send-password/:
    description: Отправляем на почту пользователю код интеграции
    post:
      body:
        application/x-www-form-urlencoded:
          properties:
            login:
              description: Логин пользователя SalesBot
              type: string
      responses:
        200:
          body:
            application/json:
              type: object
              example: |
                {
                    "status": true
                }

  /auth-telegram/:
      description: Привязка telegram ID к пользователю, по паре логин + код интеграции, сброс кода интеграции.
      post:
        body:
          application/x-www-form-urlencoded:
            properties:
              login:
                description: Логин пользователя SalesBot
                type: string
              code:
                description: Код интеграции
                type: string
              tid:
                description: Telegram ID, к которому будет осуществляться привязка
                type: string
        responses:
          200:
            body:
              application/json:
                type: object
                example: |
                  {
                      "status": true
                  }

  /set-time-zone/:
        description: Установить пользователю часовой пояс
        post:
          body:
            application/x-www-form-urlencoded:
              properties:
                tid:
                  description: Telegram ID пользователя
                  type: integer
                timezone:
                  description: Часовой пояс пользователя в формате Europe/Moscow
                  type: string
          responses:
            200:
              body:
                application/json:
                  type: object
                  example: |
                    {
                        "status": false,
                        "error": "Timezone error!"
                    },

                    {
                        "status": false,
                        "error": "Telegram ID error!"
                    },

                    {
                        "status": false,
                        "error": "User not found!"
                    },

                    {
                        "status": true,
                        "old_timezone": "test/test",
                        "new_timezone": "Europe/Moscow"
                    }
  /get-time-zone/:
          description: Получить часовой пояс пользователя ЛК
          post:
            body:
              application/x-www-form-urlencoded:
                properties:
                  tid:
                    description: Telegram ID пользователя
                    type: integer
            responses:
              200:
                body:
                  application/json:
                    type: object
                    example: |
                      {
                          "status": false,
                          "error": "Telegram ID error!"
                      },
                      {
                          "status": false,
                          "error": "User not found!"
                      },
                      {
                          "status": true,
                          "timezone": "Asia/Yekaterinburg"
                      }


/rest/accounts/v1:
  displayName: Работа с аккаунтами соц. сетей
  /user-auth/:
    description: Запись Telegram ID по логину-паролю. Список аккаунтов пользователя.
    post:
      body:
        application/x-www-form-urlencoded:
          properties:
            login:
              description: Логин пользователя SalesBot
              type: string
            password:
              description: Пароль пользователя SalesBot
              type: string
            tid:
              description: ID пользователя telegram.
              type: integer
      responses:
        200:
          body:
            application/json:
              type: object
              example: |
                {
                    "status": true,
                    "telegram_id": 123,
                    "data": [
                        {
                            "id": 1,
                            "user_id": 19,
                            "type": "instagram",
                            "data": {
                                "login": "vedensky_lx",
                                "password": "123123"
                            },
                            "status": 4,
                            "processed": 1
                        },
                        {
                            "id": 33,
                            "user_id": 19,
                            "type": "vkontakte",
                            "data": {
                                "user_name": "Александр Горбачев",
                                "user_id": "12620990",
                                "access_token": "ee9d69c94fed32d9ba03215ed9055032fc6fa22ce5fb889a9ac433e02393d24feeaef",
                                "groups": {
                                    "id": "156169448",
                                    "name": "Test app",
                                    "screen_name": "club156169448",
                                    "is_closed": "0",
                                    "type": "group",
                                    "photo_50": "https://vk.com/images/community_50.png",
                                    "photo_100": "https://vk.com/images/community_100.png",
                                    "photo_200": "https://vk.com/images/community_200.png",
                                    "$$hashKey": "00D"
                                }
                            },
                            "status": 1,
                            "processed": 1
                        },
                        {
                            "id": 44,
                            "user_id": 19,
                            "type": "vkontakte",
                            "data": {
                                "user_name": "Александр Горбачев",
                                "user_id": "12620990",
                                "access_token": "4c2d3ffde24aa1f2985ee9187ea734cecec",
                                "groups": {
                                    "id": "12620990",
                                    "name": "Стена пользователя Александр Горбачев",
                                    "photo_50": "https://vk.com/images/camera_50.png",
                                    "photo_100": "https://vk.com/images/camera_100.png",
                                    "photo_200": "https://vk.com/images/camera_200.png",
                                    "$$hashKey": "00E"
                                }
                            },
                            "status": 1,
                            "processed": 1
                        }
                    ]
                }
  /get-user-accounts/:
      description: Список аккаунтов пользователя по telegram id.
      post:
        body:
          application/x-www-form-urlencoded:
            properties:
              tid:
                description: ID пользователя telegram.
                type: integer
        responses:
          200:
            body:
              application/json:
                type: object
                example: |
                  {
                      "status": true,
                      "telegram_id": 123,
                      "data": [
                          {
                              "id": 1,
                              "user_id": 19,
                              "type": "instagram",
                              "data": {
                                  "login": "vedensky_lx",
                                  "password": "123123"
                              },
                              "status": 4,
                              "processed": 1
                          },
                          {
                              "id": 33,
                              "user_id": 19,
                              "type": "vkontakte",
                              "data": {
                                  "user_name": "Александр Горбачев",
                                  "user_id": "12620990",
                                  "access_token": "ee9d69c94fed32d9ba03215ed9055032fc6fa22ce5fb889a9ac433e02393d24feeaef",
                                  "groups": {
                                      "id": "156169448",
                                      "name": "Test app",
                                      "screen_name": "club156169448",
                                      "is_closed": "0",
                                      "type": "group",
                                      "photo_50": "https://vk.com/images/community_50.png",
                                      "photo_100": "https://vk.com/images/community_100.png",
                                      "photo_200": "https://vk.com/images/community_200.png",
                                      "$$hashKey": "00D"
                                  }
                              },
                              "status": 1,
                              "processed": 1
                          },
                          {
                              "id": 44,
                              "user_id": 19,
                              "type": "vkontakte",
                              "data": {
                                  "user_name": "Александр Горбачев",
                                  "user_id": "12620990",
                                  "access_token": "4c2d3ffde24aa1f2985ee9187ea734cecec",
                                  "groups": {
                                      "id": "12620990",
                                      "name": "Стена пользователя Александр Горбачев",
                                      "photo_50": "https://vk.com/images/camera_50.png",
                                      "photo_100": "https://vk.com/images/camera_100.png",
                                      "photo_200": "https://vk.com/images/camera_200.png",
                                      "$$hashKey": "00E"
                                  }
                              },
                              "status": 1,
                              "processed": 1
                          }
                      ]
                  }
  /set-account-status/:
    description: Изменение статуса аккаунта пользователя
    post:
      body:
        application/x-www-form-urlencoded:
          properties:
            wall_id:
              description: ID стены пользователя, к которой относится статус
              type: string
            status:
              description: "
                            null Нет данных о доступе
                            0 Ошибка доступа
                            1 Доступ активен
                          "
              type: integer
              enum: [0, 1]
      responses:
        200:
          body:
            application/json:
              type: object
              example: |
                {
                  "status": true,
                }
  /get-vk-accounts/:
      description: Получить telegram_id и access_token всех пользователей
      post:
        responses:
          200:
            body:
              application/json:
                type: object
                example: |
                  {
                      "status": true,
                      "accounts": [
                          {
                              "telegram_id": 162433937,
                              "access_token": "8d8eeed414536a7d0ed5e53f1fb9a777ef8fb17e9cf895ddbd46b952e96931470088d07a9ca254bf1ed03"
                          },
                          {
                              "telegram_id": 134330020,
                              "access_token": "ba6f2254af8fa31ff0d38cf25e17acdf18dd774f5ce95d9248ab2c571b80ac7972fd052d59c32109b8e7c"
                          },
                          {
                              "telegram_id": 45757136,
                              "access_token": "01943361e57014a1a5a6dad2a3775c6dd740fb2a84c7a4b1033f24b78da21be4c27ca68d3ce774a161b4f"
                          },
                          {
                              "telegram_id": 55302661,
                              "access_token": "51da91e1ff3addb2e1a94e1d7707d9675aa346367a4e8c8c6d2acefb8952229995835c7347c602b88a6c1"
                          }
                      ]
                  },
                  {
                      "status": false,
                      "error": "Server error!"
                  }
/rest/history/v1:
  displayName: Работа с историей действий
  /new-event/:
    description: Добавление события нового поста в соц сеть.
    post:
      body:
        application/x-www-form-urlencoded:
          properties:
            tid:
              description: ID пользователя telegram.
              type: integer
            type:
              description: Тип поста соц. сети
              type: string
              enum: ['facebook', 'vkontakte', 'instagram']
            data:
              description: Данные поста, в формате JSON
              type: string

      responses:
        200:
          body:
            application/json:
              type: object
              example: |
                {
                    "status": true
                },

                {
                    "status": false,
                    "error": "Data not found in request!"
                },

                {
                    "status": false,
                    "error": "Data is not JSON!"
                },

                {
                    "status": false,
                    "error": "Type not found in request!"
                },

                {
                    "status": false,
                    "error": "Type error! It must be equals facebook, vkontakte or instagram!"
                },

                {
                    "status": false,
                    "error": "Telegram ID not found in request!"
                },

                {
                    "status": false,
                    "error": "User not found in database!"
                }

