#%RAML 1.0
title: SalesBot
version: v1.0
baseUri: 'http://app.slavabot.ru/'
mediaType: application/json
description: "REST-api для обмена данными c SalesBot."

/rest/accounts/v1:
  displayName: Работа с аккаунтами соц. сетей
  /get-user-accounts/:
    description: Список аккаунтов пользователя
    post:
      body:
        application/x-www-form-urlencoded:
          properties:
            login:
              description: Логин пользователя SalesBot
              type: string
            password:
              description: Пароль пользователя SalesBot
              type: string
      responses:
        200:
          body:
            application/json:
              type: object
              example: |
                {
                  "status": true,
                  "data": [
                    {
                      "id": 1,
                      "user_id": 19,
                      "type": "instagram",
                      "data": {
                        "login": "login_string",
                        "password": "password_string"
                      },
                      "status": null
                    },
                    {
                      "id": 2,
                      "user_id": 19,
                      "type": "instagram",
                      "data": {
                        "login": "login_string",
                        "password": "password_string"
                      },
                      "status": null
                    }
                  ]
                }
  /set-account-status/:
    description: Изменение статуса аккаунта пользователя
    post:
      body:
        application/x-www-form-urlencoded:
          properties:
            user_id:
              description: ID пользователя SalesBot
              type: string
            account_id:
              description: ID Аккаунта соц. сети пользователя SalesBot
              type: string
            status:
              description: "
                            null Нет данных о доступе
                            0 Ошибка доступа
                            1 Доступ активен
                          "
              type: integer
              enum: [0, 1]
      responses:
        200:
          body:
            application/json:
              type: object
              example: |
                {
                  "status": true,
                }
